import { ReactNode } from 'react';
import Head from 'next/head';
import styles from './pageLayout.module.scss';
import Navbar from 'components/Navbar/Navbar';

export interface IPageLayout {
	children: ReactNode;
}

const PageLayout = ({ children }) => {
	return (
		<div className={styles.wrapper}>
			<Head>
				<title>Shop Project</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.container}>{children}</main>
		</div>
	);
};

export default PageLayout;

